version: "3"
services:

  api:
    build: .
    volumes:
      - ./app:/app
      - /app/node_modules
      - ./db:/db
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - API_REQUEST_TIMEOUT=2000
    restart: always
    command:  npm run start-dev
